#app.yaml
runtime: python39

env_variables:
  MYSQL_USERNAME: sw
  MYSQL_PASSWORD: RoI&Q/TYyic7ru$
  MYSQL_DATABASE_NAME: tag_tracking
  MYSQL_CONNECTION_NAME: bles


#PRODUCTION CLOUD VARIABLES
 # MYSQL_USERNAME: ble-database-0
  #MYSQL_PASSWORD: RoI&Q/TYyic7ru$
  #MYSQL_DATABASE_NAME: testing
 # MYSQL_CONNECTION_NAME: ble-diss-project:europe-west2:ble-database-0
  

